import { chromium } from "playwright";

const url = process.argv[2] ?? "http://localhost:5173/";
console.log("=== LAUNCHING COMPREHENSIVE END-TO-END DEEP TEST SUITE ===");
console.log("Target URL:", url);

const browser = await chromium.launch();
const context = await browser.newContext({
	viewport: { width: 390, height: 844 },
	isMobile: true,
	hasTouch: true,
});
const page = await context.newPage();

const errors = [];
page.on("pageerror", (e) => {
	console.error("❌ [UNCAUGHT_PAGE_ERROR]:", e.stack || e.message);
	errors.push(e.message);
});
page.on("console", (m) => {
	if (m.type() === "error") {
		console.error("❌ [CONSOLE_ERROR]:", m.text());
		errors.push(m.text());
	}
});

const getScenes = async () => {
	return await page.evaluate(() =>
		globalThis.__game?.scene.getScenes(true).map((s) => s.scene.key),
	);
};

const tapButton = async (text, waitMs = 2000) => {
	const clicked = await page.evaluate((btnText) => {
		const game = globalThis.__game;
		const findButton = (node) => {
			if (!node) return null;
			if (node.label?.text === btnText) return node;
			const children =
				node.list || (node.children?.list ? node.children.list : null);
			if (children) {
				for (const child of children) {
					const found = findButton(child);
					if (found) return found;
				}
			}
			return null;
		};
		for (const scene of game.scene.getScenes(true)) {
			const btn = findButton(scene);
			if (btn) {
				btn.emit("pointerdown");
				btn.emit("pointerup");
				return true;
			}
		}
		return false;
	}, text);
	if (!clicked) {
		console.warn(`Could not find button "${text}"`);
	}
	await page.waitForTimeout(waitMs);
};

const tapCanvas = async (gx, gy, waitMs = 1500) => {
	const coords = await page.evaluate(
		([x, y]) => {
			const canvas =
				globalThis.__game?.canvas || document.querySelector("canvas");
			if (!canvas) return null;
			const r = canvas.getBoundingClientRect();
			const s = r.width / 720;
			return [r.left + x * s, r.top + y * s];
		},
		[gx, gy],
	);
	if (coords) {
		await page.mouse.click(coords[0], coords[1]);
	}
	await page.waitForTimeout(waitMs);
};

// ----------------------------------------------------------------------------
// PHASE 1: BOOT & TITLE SCREEN
// ----------------------------------------------------------------------------
console.log("\n[PHASE 1] Booting and Title Screen...");
await page.goto(url);
await page.waitForTimeout(1000);
await page.evaluate(() => localStorage.clear());
await page.reload();
await page.waitForFunction(() => globalThis.__game?.scene.isActive("Title"), {
	timeout: 12000,
});

let scenes = await getScenes();
console.log("Active scenes at start:", scenes);
if (!scenes.includes("Title")) throw new Error("Expected Title scene active");
await page.screenshot({ path: "showcase/screenshots/01-title-screen.png" });

// Verify textures generated by BootScene
const texturesLoaded = await page.evaluate(() => {
	const tex = globalThis.__game?.textures;
	return {
		hasCoin: tex.exists("coin"),
		hasCoinReverse: tex.exists("coin_reverse"),
		hasSpark: tex.exists("spark"),
		hasVignette: tex.exists("vignette"),
	};
});
console.log("BootScene textures status:", texturesLoaded);
if (!texturesLoaded.hasCoin || !texturesLoaded.hasCoinReverse) {
	throw new Error("Missing coin or coin_reverse texture!");
}

// ----------------------------------------------------------------------------
// PHASE 2: LEADER SELECTION & CAROUSEL
// ----------------------------------------------------------------------------
console.log("\n[PHASE 2] Leader Selection Carousel...");
await page.waitForTimeout(2000);
console.log("Tapping Begin Your Reign...");
await tapButton("Begin Your Reign", 2500);

scenes = await getScenes();
console.log("Active scenes after Begin:", scenes);
if (!scenes.includes("Select"))
	throw new Error("Failed to transition to Select");

// Verify Leader Carousel state
const selectState = await page.evaluate(() => {
	const sel = globalThis.__game?.scene.getScene("Select");
	return {
		currentIndex: sel?.index,
		leadersCount: sel?.leaders?.length,
		activeLeaderName: sel?.leaders?.[sel?.index]?.name,
	};
});
console.log("Select Scene state:", selectState);

// Slide to Napoleon (step +1)
console.log("Stepping carousel to next leader...");
await page.evaluate(() => {
	globalThis.__game?.scene.getScene("Select")?.step(1);
});
await page.waitForTimeout(1000);
await page.screenshot({ path: "showcase/screenshots/02-leader-carousel.png" });

// Tap "Take the Throne"
console.log("Taking the throne...");
await page.evaluate(() => {
	const sel = globalThis.__game?.scene.getScene("Select");
	sel?.begin();
});
await page.waitForFunction(() => globalThis.__game?.scene.isActive("Court"), {
	timeout: 12000,
});
scenes = await getScenes();
console.log("Active scenes after taking throne:", scenes);
if (!scenes.includes("Court")) throw new Error("Failed to enter Court scene");

// ----------------------------------------------------------------------------
// PHASE 3: COURT GAMEPLAY LOOP (FULL TURNS)
// ----------------------------------------------------------------------------
console.log("\n[PHASE 3] Playing through Court dilemma turns...");

// Skip Chapter 1 card
console.log("Waiting for Chapter 1 card and tapping to advance...");
await page.waitForTimeout(2500);
await tapCanvas(360, 700, 2000); // Tap to skip chapter intro

for (let turn = 1; turn <= 3; turn++) {
	console.log(`\n--- Playing Turn ${turn} ---`);

	// Wait for advisor speech and skip it by tapping
	await page.waitForTimeout(2500);
	if (turn === 1) {
		await page.screenshot({
			path: "showcase/screenshots/03-court-advisor-speaking.png",
		});
	}
	await tapCanvas(360, 700, 1500); // Skip main speech
	await tapCanvas(360, 700, 1500); // Skip rebuttal speech if present

	// Wait for Choice Cards to settle
	await page.waitForTimeout(1500);
	if (turn === 1) {
		await page.screenshot({ path: "showcase/screenshots/04-choice-cards.png" });
	}

	// Verify Court turn state
	const courtTurn = await page.evaluate(() => {
		const c = globalThis.__game?.scene.getScene("Court");
		return {
			turnIndex: c?.g?.turnIndex,
			gold: c?.g?.stats?.gold,
			stability: c?.g?.stats?.stability,
			legacy: c?.g?.stats?.legacy,
		};
	});
	console.log(`Turn ${turn} state:`, courtTurn);

	// Pick Choice 0
	console.log("Picking choice 0...");
	await page.evaluate(() => {
		const court = globalThis.__game?.scene.getScene("Court");
		const list = court?.children?.list || court?.sys?.displayList?.list || [];
		for (const child of list) {
			if (child.cards && child.cards.length > 0) {
				child.cards[0].emit("pointerdown");
				child.cards[0].emit("pointerup");
				break;
			}
		}
	});
	await page.waitForTimeout(2500);

	// Oracle Wager appears
	console.log("Oracle appeared! Placing wager on Historical Path...");
	await page.waitForTimeout(1500);
	if (turn === 1) {
		await page.screenshot({ path: "showcase/screenshots/05-oracle-wager.png" });
	}
	await page.evaluate(() => {
		const court = globalThis.__game?.scene.getScene("Court");
		const list = court?.children?.list || court?.sys?.displayList?.list || [];
		for (const child of list) {
			if (child.tablets && child.tablets.length > 0) {
				child.tablets[0].emit("pointerdown");
				child.tablets[0].emit("pointerup");
				break;
			}
		}
	});
	await page.waitForTimeout(4500); // Let 3D tumbling coin flip and shockwave resolve

	// Reveal Parchment appears
	console.log("Reveal parchment appeared. Advancing...");
	await page.waitForTimeout(2000);
	if (turn === 1) {
		await page.screenshot({
			path: "showcase/screenshots/06-historical-reveal.png",
		});
	}
	await tapCanvas(360, 700, 1000); // Skip narrator audio
	const _advanced =
		(await tapButton("Next council", 2000)) ||
		(await tapButton("Hear the verdict", 2000));

	console.log(`Turn ${turn} resolved successfully!`);
}

// ----------------------------------------------------------------------------
// PHASE 4: VERDICT SCENE & SCORECARD
// ----------------------------------------------------------------------------
console.log("\n[PHASE 4] Testing Verdict Scene & Scorecard Count-up...");
// Fast forward to end of chapter
await page.evaluate(() => {
	const raw = localStorage.getItem("chronicle.save");
	const g = JSON.parse(raw);
	g.turnIndex = 5;
	g.stats = { gold: 8, stability: 7, legacy: 9 };
	localStorage.setItem("chronicle.save", JSON.stringify(g));
	const game = globalThis.__game;
	for (const s of game.scene.getScenes(true)) s.scene.stop();
	game.scene.start("Verdict");
});

// Wait for verdict deliberation to complete and title to be rendered
await page.waitForFunction(
	() => {
		const v = globalThis.__game?.scene.getScene("Verdict");
		const list = [];
		const walk = (node) => {
			if (!node) return;
			if (node.text) list.push(node.text);
			if (node.label?.text) list.push(node.label.text);
			const children =
				node.list || (node.children?.list ? node.children.list : null);
			if (children) {
				for (const child of children) walk(child);
			}
		};
		walk(v);
		return list.includes("THE VERDICT") || list.includes("REIGN COLLAPSED");
	},
	{ timeout: 15000 },
);

await page.waitForTimeout(2000);
await tapCanvas(360, 700, 1000); // Skip narrator
await tapCanvas(360, 700, 2000); // Skip leader
await page.screenshot({
	path: "showcase/screenshots/07-verdict-scorecard.png",
});

scenes = await getScenes();
console.log("Verdict active scenes:", scenes);
if (!scenes.includes("Verdict"))
	throw new Error("Expected Verdict scene active");

const verdictState = await page.evaluate(() => {
	const v = globalThis.__game?.scene.getScene("Verdict");
	const getAllTexts = (root) => {
		const list = [];
		const walk = (node) => {
			if (!node) return;
			if (node.text) list.push(node.text);
			if (node.label?.text) list.push(node.label.text);
			const children =
				node.list || (node.children?.list ? node.children.list : null);
			if (children) {
				for (const child of children) walk(child);
			}
		};
		walk(root);
		return list;
	};
	const texts = getAllTexts(v);
	return {
		hasScorecard: texts.some((t) => t.includes("matched history")),
		allTexts: texts.slice(0, 10),
	};
});
console.log("Verdict Scene inspection:", verdictState);

// ----------------------------------------------------------------------------
// PHASE 5: GAME OVER / COLLAPSE MECHANIC
// ----------------------------------------------------------------------------
console.log("\n[PHASE 5] Testing Game Over / Reign Collapse (Zero Gold)...");
await page.goto(url);
await page.waitForTimeout(2000);

await page.evaluate(() => {
	const raw = localStorage.getItem("chronicle.save");
	const g = raw
		? JSON.parse(raw)
		: {
				leader: {
					id: "napoleon",
					name: "Napoleon Bonaparte",
					civ: "French Empire",
					era: "1799–1815",
					quote: "Impossible",
					voice: "6MFfc37kq0sBjBjy",
					palette: { primary: "#1f3a93", accent: "#d4af37", bg: "#0d1633" },
					advisors: [],
				},
				season: 1,
				turnIndex: 5,
				stats: { gold: 0, stability: 5, legacy: 5 },
				trust: { war: 0, gold: 0, faith: 0 },
				combo: 0,
				history: [
					{
						year: "1800",
						title: "Test",
						chosen: "Test",
						historical: true,
						matched: true,
						advisor: "war",
						followedAdvisor: true,
					},
				],
				collapse: "bankruptcy",
				chapter: null,
				liar: null,
				liedLastTurn: false,
				seasonsPlayed: 1,
			};
	g.collapse = "bankruptcy";
	g.stats = { gold: 0, stability: 5, legacy: 3 };
	localStorage.setItem("chronicle.save", JSON.stringify(g));
});
await page.reload();
await page.waitForFunction(() => globalThis.__game?.scene.isActive("Title"));

// Tap Continue: Napoleon Bonaparte to see the Verdict / Court resume
console.log("Resuming saved reign...");
await tapButton("Continue: Napoleon Bonaparte", 4000);

// If in Court, it detects collapse and transitions to Verdict
await page.waitForFunction(
	() => {
		return globalThis.__game?.scene.isActive("Verdict");
	},
	{ timeout: 15000 },
);

await page.waitForFunction(
	() => {
		const v = globalThis.__game?.scene.getScene("Verdict");
		const getAllTexts = (root) => {
			const list = [];
			const walk = (node) => {
				if (!node) return;
				if (node.text) list.push(node.text);
				if (node.label?.text) list.push(node.label.text);
				const children =
					node.list || (node.children?.list ? node.children.list : null);
				if (children) {
					for (const child of children) walk(child);
				}
			};
			walk(root);
			return list;
		};
		const texts = getAllTexts(v);
		return texts.includes("Try Again");
	},
	{ timeout: 15000 },
);

const collapseState = await page.evaluate(() => {
	const v = globalThis.__game?.scene.getScene("Verdict");
	const getAllTexts = (root) => {
		const list = [];
		const walk = (node) => {
			if (!node) return;
			if (node.text) list.push(node.text);
			if (node.label?.text) list.push(node.label.text);
			const children =
				node.list || (node.children?.list ? node.children.list : null);
			if (children) {
				for (const child of children) walk(child);
			}
		};
		walk(root);
		return list;
	};
	const texts = getAllTexts(v);
	return {
		hasTryAgain: texts.includes("Try Again"),
		hasCollapsedHeader: texts.includes("REIGN COLLAPSED"),
		texts: texts.slice(0, 8),
	};
});
console.log("Collapse verification:", collapseState);
if (!collapseState.hasTryAgain || !collapseState.hasCollapsedHeader) {
	throw new Error("Failed to render collapse Game Over state in Verdict!");
}

// ----------------------------------------------------------------------------
// PHASE 6: AUXILIARY SCENES (CODEX, CHRONICLE, SETTINGS)
// ----------------------------------------------------------------------------
console.log(
	"\n[PHASE 6] Testing Auxiliary Scenes (Codex, Chronicle, Settings)...",
);
for (const sceneName of ["Codex", "Chronicle", "Settings"]) {
	await page.evaluate(
		([sc]) => {
			const game = globalThis.__game;
			for (const s of game.scene.getScenes(true)) s.scene.stop();
			game.scene.start(sc);
		},
		[sceneName],
	);
	await page.waitForTimeout(2000);
	const active = await getScenes();
	console.log(`Auxiliary ${sceneName} -> active scenes:`, active);
	if (!active.includes(sceneName)) {
		throw new Error(`Failed to activate ${sceneName}`);
	}
}

await browser.close();

console.log("\n=======================================================");
if (errors.length === 0) {
	console.log("🌟 ALL 6 PHASES PASSED WITH ZERO ERRORS! 100% CLEAN!");
} else {
	console.error("❌ Errors detected during test:", errors);
	process.exit(1);
}
console.log("=======================================================");
